import type { Metadata } from "next";

import "./globals.css";

// font imports
import { Inter } from "next/font/google";

// font definitions
const inter = Inter({ subsets: ["latin"] });

// comoponents
import Header from "../components/header/header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
